% Codigo do experimento do duto de impedancia
clear('all');
%close all;
clc;
format longe;

% Definindo constantes
% [K] - Temperatura do Ambiente de Medição
temperatura_ambiente = 25+273.15;      
% [m/s] - Velocidade do Som no Ar                                                        
velocidade_som = 343.2*sqrt(temperatura_ambiente/293);
% Constante para o Cálculo da Freq. de Corte
constante_frequencia_corte = 0.5;
% [m] - Diâmetro Interno do Tudo
diametro_tubo_interno = 0.027;
% [m] - Distância do Microfone mais Distante à Amostra em Teste
distancia_microfone_distante = 0.0673;
% [m] - Distância entre os Dois Microfones
distancia_entre_microfones = 0.024;                                                                  
% [m] - Distância da Amostra ao Microfone mais Próximo
distancia_microfone_perto = distancia_microfone_distante - distancia_entre_microfones;                                                                  
% [Hz] - Frequência de Corte do Tubo de Impedância, para esta Configuração de Teste.
frequencia_corte_tubo = (1.84*velocidade_som)/(pi*diametro_tubo_interno);

% Captando os mifrofones para primeira medicao
%% Primeira posicao
funcao_transferencia_medicao_1_posicao_1 = ... 
textread('medicaoladerocha1_pos1.txt');
frequencias = funcao_transferencia_medicao_1_posicao_1(:,2);
funcao_transferencia_medicao_1_posicao_1 = ... 
funcao_transferencia_medicao_1_posicao_1(:,3) + ...
funcao_transferencia_medicao_1_posicao_1(:,4)*i;
%% Segunda posicao
funcao_transferencia_medicao_1_posicao_2 = ... 
textread('medicaoladerocha1_pos2.txt');
funcao_transferencia_medicao_1_posicao_2 = ... 
funcao_transferencia_medicao_1_posicao_2(:,3) + ...
funcao_transferencia_medicao_1_posicao_2(:,4)*i;
funcao_transferencia_medicao_1_posicao_2 = ... 
funcao_transferencia_medicao_1_posicao_2;

% Captando os mifrofones para segunda medicao
%% Primeira posicao
funcao_transferencia_medicao_2_posicao_1 = ... 
textread('medicaoladerocha2_pos1.txt');
funcao_transferencia_medicao_2_posicao_1 = ... 
funcao_transferencia_medicao_2_posicao_1(:,3) + ...
funcao_transferencia_medicao_2_posicao_1(:,4)*i;
%% Segunda posicao
funcao_transferencia_medicao_2_posicao_2 = ... 
textread('medicaoladerocha2_pos2.txt');
funcao_transferencia_medicao_2_posicao_2 = ... 
funcao_transferencia_medicao_2_posicao_2(:,3) + ...
funcao_transferencia_medicao_2_posicao_2(:,4)*i;

% Captando os mifrofones para terceira medicao
%% Primeira posicao
funcao_transferencia_medicao_3_posicao_1 = ... 
textread('medicaoladerocha3_pos1.txt');
funcao_transferencia_medicao_3_posicao_1 = ... 
funcao_transferencia_medicao_3_posicao_1(:,3) + ...
funcao_transferencia_medicao_3_posicao_1(:,4)*i;
%% Segunda posicao
funcao_transferencia_medicao_3_posicao_2 = ... 
textread('medicaoladerocha3_pos2.txt');
funcao_transferencia_medicao_3_posicao_2 = ... 
funcao_transferencia_medicao_3_posicao_2(:,3) + ...
funcao_transferencia_medicao_3_posicao_2(:,4)*i;
funcao_transferencia_medicao_3_posicao_2 = ... 
funcao_transferencia_medicao_3_posicao_2;

% Captando os mifrofones para medicao sem amostra
%% Primeira posicao
funcao_transferencia_medicao_4_posicao_1 = ... 
textread('medicaosemamostra2_pos1.txt');
funcao_transferencia_medicao_4_posicao_1 = ... 
funcao_transferencia_medicao_4_posicao_1(:,3) + ...
funcao_transferencia_medicao_4_posicao_1(:,4)*i;
%% Segunda posicao
funcao_transferencia_medicao_4_posicao_2 = ... 
textread('medicaosemamostra2_pos2.txt');
funcao_transferencia_medicao_4_posicao_2 = ... 
funcao_transferencia_medicao_4_posicao_2(:,3) + ...
funcao_transferencia_medicao_4_posicao_2(:,4)*i;
funcao_transferencia_medicao_4_posicao_2 = ... 
funcao_transferencia_medicao_4_posicao_2;

% Correcao da fase para todas as medicoes
%% medicao 1
funcao_transferencia_medicao_1_corrigida = ...
(funcao_transferencia_medicao_1_posicao_1.^0.5)./ ...
(funcao_transferencia_medicao_1_posicao_2.^0.5);
%% medicao 2
funcao_transferencia_medicao_2_corrigida = ...
(funcao_transferencia_medicao_2_posicao_1.^0.5)./ ...
funcao_transferencia_medicao_2_posicao_2.^0.5;
%% medicao 3
funcao_transferencia_medicao_3_corrigida = ...
(funcao_transferencia_medicao_3_posicao_1.^0.5)./ ...
funcao_transferencia_medicao_3_posicao_2.^0.5;

% Calculo das Funcoes de Transferencia: ondas incidentes
numero_onda_por_frequencia = (2*pi.*frequencias)/velocidade_som;
% Constante de incidencia
constantes_incidencia = exp(-1*i* ... 
numero_onda_por_frequencia*(distancia_entre_microfones));
% Constante de reflexao
constantes_reflexao = exp(i* ... 
numero_onda_por_frequencia*(distancia_entre_microfones));

% Calculo coeficientes de reflexao
% Medicao 1
%r1 = ((H_12-H_Ii)./(H_Ri-H_12)).*exp(2*1i*k0*x1);
coeficientes_reflexao_medicao_1 = ...
((funcao_transferencia_medicao_1_corrigida - constantes_incidencia) ...
./(constantes_reflexao - funcao_transferencia_medicao_1_corrigida)).* ...
exp(2*i*numero_onda_por_frequencia*distancia_microfone_distante);
% Medicao 2
coeficientes_reflexao_medicao_2 = ...
((funcao_transferencia_medicao_2_corrigida - constantes_incidencia) ...
./(constantes_reflexao - funcao_transferencia_medicao_2_corrigida)).* ...
exp(2*i*numero_onda_por_frequencia*distancia_microfone_distante);
% Medicao 3
coeficientes_reflexao_medicao_3 = ...
((funcao_transferencia_medicao_3_corrigida - constantes_incidencia) ...
./(constantes_reflexao - funcao_transferencia_medicao_3_corrigida)).* ...
exp(2*i*numero_onda_por_frequencia*distancia_microfone_distante);

% Cálculo do Coeficiente de Absorção da Lã de Vidro (verde)
% Medicao 1
coeficientes_absorcao_medicao_1 = ... 
1 - (abs(coeficientes_reflexao_medicao_1)).^2;
% Medicao 2
coeficientes_absorcao_medicao_2 = ... 
1 - (abs(coeficientes_reflexao_medicao_2)).^2;
% Medicao 3
coeficientes_absorcao_medicao_3 = ... 
1 - (abs(coeficientes_reflexao_medicao_3)).^2;

%% medicao 4
funcao_transferencia_medicao_4_corrigida = ...
(funcao_transferencia_medicao_4_posicao_1.^0.5)./ ...
(funcao_transferencia_medicao_4_posicao_2.^0.5);
% Medicao 4
coeficientes_reflexao_medicao_4 = ...
((funcao_transferencia_medicao_4_corrigida - constantes_incidencia) ...
./(constantes_reflexao - funcao_transferencia_medicao_4_corrigida)).* ...
exp(2*i*numero_onda_por_frequencia*distancia_microfone_distante);
% Medicao 4
coeficientes_absorcao_medicao_4 = ... 
1 - (abs(coeficientes_reflexao_medicao_4)).^2;


figure;
colors{1} = 'blue';
colors{2} = 'red';
colors{3} = 'green';
colors{4} = 'black';
for grafico = 1:4
	plot(frequencias, ...
	eval(['coeficientes_absorcao_medicao_', num2str(grafico)]), ...
	colors{grafico},'linewidth',2);
	hold on;
	ylim([0 1]);
end
legend('Coeficientes de Absorção Amostra 1: 25.2 mm', ... 
'Coeficientes de Absorção Amostra 2: 25.8 mm', ... 
'Coeficientes de Absorção Amostra 3: 25.6 mm', 'Coeficientes Sem Amostra');
xlabel('Frequência (Hz)');
ylabel('Coeficiente de Absorção \alpha');
grid on;
